name = "Scats"
uuid = "a40fd361-391c-496e-af78-06d474f782f1"
authors = ["Pavel Sobolev <paveloom@mail.ru>"]
version = "0.2.0"

[deps]
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
OffsetArrays = "1.0.4"
julia = "1.4"
